baseURL: "/"
languageCode: 'en-us'
title: 'Mrrakc'
theme: 'PaperMod'
description: 'Sharing the love for Morocco with the world'


minify:
    disableXML: true
    # minifyOutput: true

menu:
  main:
    - identifier: categories
      name: Categories
      url: /categories
      weight: -100
    - identifier: regions
      name: Regions
      url: /regions
      weight: -90
    - identifier: blog
      name: Blog
      url: /posts
      weight: -80

taxonomies:
  category: 'categories'
  tag: 'tags'
  region: 'regions'
